version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: N0KIy6FnS7IW4pEo1Iw8
      POSTGRES_DB: postgres

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: N0KIy6FnS7IW4pEo1Iw8
      POSTGRES_DB: postgres
