from django.db import models

class Park(models.Model):
    name = models.CharField(max_length=200, blank = True, null = True)
    location = models.CharField(max_length=500, blank = True, null = True)
    timezone = models.CharField(max_length=100, blank = True, null = True)
    address_street = models.CharField(max_length=200, blank = True, null = True)
    address_comment = models.CharField(max_length=500, blank = True, null = True)
    full_address = models.CharField(max_length=500, blank = True, null = True)
    map_position = models.CharField(max_length=500, blank = True, null = True)
    description = models.CharField(max_length=500, blank = True, null = True)
    website = models.CharField(max_length=500, blank = True, null = True)
    mail = models.CharField(max_length=500, blank = True, null = True)
    phones = models.CharField(max_length=500, blank = True, null = True)
    image = models.CharField(max_length=500, blank = True, null = True)
    gallery = models.CharField(max_length=500, blank = True, null = True)
    category_type = models.CharField(max_length=500, blank = True, null = True)
    category = models.CharField(max_length=500, blank = True, null = True)
    organization_name = models.CharField(max_length=500, blank = True, null = True)
    organization_address = models.CharField(max_length=500, blank = True, null = True)
    organization_timezone = models.CharField(max_length=500, blank = True, null = True)
    organization_address_street = models.CharField(max_length=500, blank = True, null = True)
    organization_address_comment = models.CharField(max_length=500, blank = True, null = True)
    organization_address_full_address = models.CharField(max_length=500, blank = True, null = True)
    organization_map_position = models.CharField(max_length=500, blank = True, null = True)
    organization_inn = models.CharField(max_length=500, blank = True, null = True)
    organization_type = models.CharField(max_length=500, blank = True, null = True)
    organization_subordination_name = models.CharField(max_length=500, blank = True, null = True)
    organization_subordination_timezone = models.CharField(max_length=500, blank = True, null = True)
    organization_social_groups = models.CharField(max_length=500, blank = True, null = True)
    organization_id = models.CharField(max_length=500, blank = True, null = True)
    tags = models.CharField(max_length=500, blank = True, null = True)
    video_hostings = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_mon = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_tue = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_wed = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_thu = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_fri = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_sat = models.CharField(max_length=500, blank = True, null = True)
    working_schedule_sun = models.CharField(max_length=500, blank = True, null = True)
    art_type = models.CharField(max_length=500, blank = True, null = True)
    audience_type = models.CharField(max_length=500, blank = True, null = True)
    language = models.CharField(max_length=500, blank = True, null = True)
    professional_level = models.CharField(max_length=500, blank = True, null = True)
    virtual_tour = models.CharField(max_length=500, blank = True, null = True)
    types = models.CharField(max_length=500, blank = True, null = True)
    start = models.CharField(max_length=500, blank = True, null = True)
    general_id = models.CharField(max_length=500, blank = True, null = True)
    service_name = models.CharField(max_length=500, blank = True, null = True)
    eipsk_id = models.CharField(max_length=500, blank = True, null = True)
    culturarf = models.CharField(max_length=500, blank = True, null = True)
    goscatalog_id = models.CharField(max_length=500, blank = True, null = True)
    statistic = models.CharField(max_length=500, blank = True, null = True)
    create_date = models.DateTimeField()
    update_date = models.DateTimeField()

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'parks'
