from rest_framework import serializers
from .models import Park


class ParkSerializer(serializers.ModelSerializer):
    class Meta:
        model = Park
        fields = [
            "id",
            "name",
            "location",
            "timezone",
            "address_street",
            "address_comment",
            "full_address",
            "map_position",
            "description",
            "website",
            "mail",
            "phones",
            "image",
            "gallery",
            "category_type",
            "category",
            "organization_name",
            "organization_address",
            "organization_timezone",
            "organization_address_street",
            "organization_address_comment",
            "organization_address_full_address",
            "organization_map_position",
            "organization_inn",
            "organization_type",
            "organization_subordination_name",
            "organization_subordination_timezone",
            "organization_social_groups",
            "organization_id",
            "tags",
            "video_hostings",
            "working_schedule_mon",
            "working_schedule_tue",
            "working_schedule_wed",
            "working_schedule_thu",
            "working_schedule_fri",
            "working_schedule_sat",
            "working_schedule_sun",
            "art_type",
            "audience_type",
            "language",
            "professional_level",
            "virtual_tour",
            "types",
            "start",
            "general_id",
            "service_name",
            "eipsk_id",
            "culturarf",
            "goscatalog_id",
            "statistic",
            "create_date",
            "update_date",
        ]
